// ── HIVE Handbook data
// Loads from data/case-studies.json when available, falls back to hardcoded seed data.
// All consumers import from here — never directly from the JSON file.

/** From hive.article_cards: used on search result cards when card is generated for this article. */
export type ArticleCardData = {
  transferability_contexts: string[];
  key_insight: string;
  investment_band: string;
  uk_transferability: string;
};

export type CaseStudy = {
  id: string;
  title: string;
  organisation: string;
  sector: string;
  hook: string;
  hazards: { cause: string[]; effect: string[] };
  summary: string;
  transferability: string;
  transferabilityNote: string;
  ukApplicability: string[];
  insight: string;
  measures: string[];
  assets: string[];
  tags: string[];
  location: string;
  ukRegion: string;
  year: string;
  cost: string;
  costBand: string;
  placeholder?: boolean;
  sections?: Record<string, string>;
  source_pdf_url?: string;
  /** When present, search result card shows "Where this applies" + "Key insight" instead of UK applicability. */
  articleCard?: ArticleCardData;
};

/** TRIB PDF URL: use explicit source_pdf_url or build from id + title. */
export function getCaseStudyPdfUrl(cs: { id: string; title: string; source_pdf_url?: string }): string {
  if (cs.source_pdf_url) return cs.source_pdf_url;
  const slug = cs.id.replace(/_/g, " ") + "_" + cs.title;
  return "https://trib.org.uk/documents/" + encodeURIComponent(slug) + ".pdf";
}

export type MarqueeEntry = {
  id: string;
  title: string;
  sector: string;
  measure: string;
  hazards: string[];
  hook: string;
  caseStudyId?: string;
};

export const SECTORS = ["Rail", "Aviation", "Maritime", "Highways"] as const;

export const HAZARDS_CAUSE = ["Heavy rainfall", "High temperatures", "Storms", "Sea level rise", "Drought", "Freeze-thaw"] as const;

function normaliseBulletGlyphs(input: string): string {
  if (!input) return "";
  // Fix Word/PDF "Symbol/Wingdings" bullet (often rendered as tofu squares in web fonts)
  return input
    .replace(/\uF0B7/g, "•")
    .replace(//g, "•")
    .replace(/\s*•\s*/g, "• "); // ensure consistent spacing
}

function normaliseSections(sections?: Record<string, string>): Record<string, string> | undefined {
  if (!sections) return sections;
  const out: Record<string, string> = {};
  for (const [k, v] of Object.entries(sections)) {
    out[k] = normaliseBulletGlyphs(v ?? "");
  }
  return out;
}

export const MARQUEE_ENTRIES: MarqueeEntry[] = [
  { id: "01", title: "Port of Calais Extension", sector: "Maritime", measure: "Port extension", hazards: ["Sea level rise", "Storm surge"], hook: "+65ha reclaimed · €863m (2021)", caseStudyId: "ID_01" },
  { id: "02", title: "Port of Calais Sea Defence", sector: "Maritime", measure: "Sea defence", hazards: ["Sea level rise", "Storm surge"], hook: "3.3km seawall · 100ha basin", caseStudyId: "ID_01" },
  { id: "03", title: "Prince Edward Island", sector: "Highways", measure: "Intertidal reefs", hazards: ["Coastal erosion", "Storm surge"], hook: "2,400 tonnes sandstone reefs" },
  { id: "04", title: "Copenhagen Metro – Waterproofing", sector: "Rail", measure: "Waterproof tunnel designs", hazards: ["Flooding", "Sea waves"], hook: "Waterproof walls up to 2.3m" },
  { id: "05", title: "Copenhagen Metro – Drainage", sector: "Rail", measure: "Improved drainage", hazards: ["Flooding", "Heavy rainfall"], hook: "Drains + pumping systems" },
  { id: "06", title: "Panama Canal Water Saving", sector: "Maritime", measure: "Water optimisation", hazards: ["Drought"], hook: "Strategic water conservation" },
  { id: "07", title: "Albert Canal – Archimedes Screws", sector: "Maritime", measure: "Archimedes screws", hazards: ["Drought", "Water shortage"], hook: "Largest screws in the world" },
  { id: "08", title: "Albert Canal – Hydroelectric", sector: "Maritime", measure: "Hydroelectric power", hazards: ["High water levels"], hook: "Dual pump + power generation" },
  { id: "09", title: "ÖBB – Slope Stabilisation", sector: "Rail", measure: "Slope stabilisation", hazards: ["Landslide", "Rockfall"], hook: "3,370 hectares protected forest", caseStudyId: "ID_06" },
  { id: "10", title: "ÖBB – Rockfall Barriers", sector: "Rail", measure: "Rockfall barriers", hazards: ["Rockfall", "Avalanche"], hook: "212km barriers installed", caseStudyId: "ID_06" },
  { id: "11", title: "ÖBB – Flood Defences", sector: "Rail", measure: "Flood defences", hazards: ["Flooding", "Extreme precipitation"], hook: "Retention basins + drainage", caseStudyId: "ID_06" },
  { id: "12", title: "ÖBB – Early Warning Systems", sector: "Rail", measure: "Early warning systems", hazards: ["Multiple hazards"], hook: "Geotechnical sensors + forecasting", caseStudyId: "ID_06" },
  { id: "13", title: "MTA Saint George – Flood Protection", sector: "Rail", measure: "Flood protection devices", hazards: ["Flooding", "Storm surge"], hook: "3,000+ flood barriers installed" },
  { id: "14", title: "MTA – Elevated Equipment", sector: "Rail", measure: "Elevating equipment", hazards: ["Flooding", "Hurricane"], hook: "Signal room elevated 12 feet" },
  { id: "15", title: "CIPA Port – Wharf Height", sector: "Maritime", measure: "Wharf height increase", hazards: ["Sea level rise", "Storm surge"], hook: "+0.5m with 0.5m flexibility" },
  { id: "16", title: "CIPA Port – Rock Armour", sector: "Maritime", measure: "Rock armour", hazards: ["Storm surge", "Erosion"], hook: "92m breakwater extension" },
  { id: "17", title: "Infrabel – Tension Release Devices", sector: "Rail", measure: "Tension release devices", hazards: ["Extreme heat", "Extreme cold"], hook: "Prevents buckling + fracturing" },
  { id: "18", title: "Infrabel – Storm Basins", sector: "Rail", measure: "Storm basins", hazards: ["Flooding"], hook: "Flood-prone area mitigation" },
  { id: "19", title: "Deutsche Bahn – ICE 4 Trains", sector: "Rail", measure: "Air-conditioned trains", hazards: ["Extreme heat"], hook: "AC rated to 45°C", caseStudyId: "ID_11" },
  { id: "20", title: "Deutsche Bahn – Vegetation Mgmt", sector: "Rail", measure: "Vegetation management", hazards: ["Storms", "Falling trees"], hook: "26,000+ trees planted", caseStudyId: "ID_11" },
  { id: "21", title: "Deutsche Bahn – Sensors", sector: "Rail", measure: "Environmental sensors", hazards: ["Multiple hazards"], hook: "IoT monitoring for prevention", caseStudyId: "ID_11" },
  { id: "22", title: "Leeds Flood Alleviation – NFM", sector: "Highways", measure: "Natural Flood Management", hazards: ["Flooding"], hook: "500,000 trees planted" },
  { id: "23", title: "Leeds Flood Alleviation – Engineering", sector: "Highways", measure: "Traditional engineering", hazards: ["Flooding"], hook: "1.8M m³ flood storage" },
  { id: "24", title: "TfL Marylebone – SuDS", sector: "Highways", measure: "Sustainable Drainage", hazards: ["Flooding", "Heavy rainfall"], hook: "3,500m² rainwater collection" },
  { id: "25", title: "Adelaide Airport Irrigation", sector: "Aviation", measure: "Irrigation", hazards: ["Extreme heat"], hook: "200 hectares irrigated land" },
  { id: "26", title: "Gatwick – Clays Lake Scheme", sector: "Aviation", measure: "Flood storage reservoirs", hazards: ["Flooding"], hook: "400,000 m³ capacity" },
  { id: "27", title: "Network Rail Conwy Valley", sector: "Rail", measure: "Earthworks", hazards: ["Flooding", "Washout"], hook: "16,000 tonnes rock armour" },
  { id: "28", title: "Phoenix Cool Pavements", sector: "Highways", measure: "Cool pavement technology", hazards: ["Extreme heat"], hook: "100+ miles treated", caseStudyId: "ID_19" },
  { id: "29", title: "South Australia – Fire Suppression", sector: "Highways", measure: "Ventilation systems", hazards: ["Wildfire", "Smoke"], hook: "23 new exhaust fans" },
  { id: "30", title: "Qatar – Pumping Station", sector: "Aviation", measure: "Pumping station", hazards: ["Flooding", "Storm"], hook: "10km undersea outfall tunnel" },
  { id: "31", title: "Hammersmith Bridge Cooling", sector: "Highways", measure: "Bridge deck cooling", hazards: ["Extreme heat"], hook: "Water spray cooling system" },
  { id: "32", title: "Heathrow Balancing Pond", sector: "Aviation", measure: "Water management", hazards: ["Flooding", "Drought"], hook: "Year-round flow control · £2.1m", caseStudyId: "ID_32" },
  { id: "33", title: "Heathrow Climate-Resilient Grass", sector: "Aviation", measure: "Climate-resilient grass", hazards: ["Drought", "Extreme heat"], hook: "Deeper root systems" },
  { id: "34", title: "Santa Barbara Debris Basin", sector: "Highways", measure: "Debris basin", hazards: ["Heavy rainfall", "Debris flow"], hook: "6-acre capture basin" },
  { id: "35", title: "Croydon Grid Flood Defence", sector: "Energy", measure: "Flood barriers + equipment sealing", hazards: ["High winds", "Flooding"], hook: "69,000 customers protected · £800k", caseStudyId: "ID_UKPN_01" },
  { id: "36", title: "Queensland Foamed Bitumen", sector: "Highways", measure: "Foamed bitumen", hazards: ["Flooding"], hook: "Water-resistant pavement" },
  { id: "37", title: "Network Rail – CWR Tracks", sector: "Rail", measure: "Thermally resilient tracks", hazards: ["Extreme heat"], hook: "Continuous Welded Rail" },
  { id: "38", title: "Network Rail – Auto Monitoring", sector: "Rail", measure: "Automated track monitoring", hazards: ["Extreme heat"], hook: "Real-time temperature sensors" },
  { id: "39", title: "Network Rail – Water Cooling", sector: "Rail", measure: "Water cooling", hazards: ["Extreme heat"], hook: "White paint + water · 5–10°C reduction" },
  { id: "40", title: "Network Rail – OLE Auto-tension", sector: "Rail", measure: "Auto-tension overhead wires", hazards: ["Extreme heat"], hook: "Spring tensioners to 38°C" },
  { id: "41", title: "LA Metro – Hardening Infrastructure", sector: "Rail", measure: "Hardening infrastructure", hazards: ["Flooding", "Wildfire"], hook: "Raised rail + wetlands" },
  { id: "42", title: "LA Metro – Operational Adjustments", sector: "Rail", measure: "Adjusting operations", hazards: ["Flooding", "Wildfire"], hook: "Blue water detours" },
  { id: "43", title: "LA Metro – Wetlands Park", sector: "Rail", measure: "Relocating infrastructure", hazards: ["Flooding", "Stormwater"], hook: "46-acre wetlands park" },
  { id: "44", title: "Sheffield Grey to Green", sector: "Highways", measure: "SuDS", hazards: ["Heavy rainfall", "Flooding"], hook: "60% grey to green · 1.5km", caseStudyId: "ID_40" },
  { id: "45", title: "Network Rail Dawlish Sea Wall", sector: "Rail", measure: "Sea wall", hazards: ["Waves", "Storm surge"], hook: "8m height with recurve design" },
  { id: "46", title: "TfL Rainwater Harvesting", sector: "Rail", measure: "Rainwater harvesting", hazards: ["Water runoff"], hook: "23,000 m³ recycled annually" },
  { id: "47", title: "Thames Tidal Barrier", sector: "Multiple", measure: "Tidal barriers", hazards: ["Flooding", "Storm surge"], hook: "520m · protects 1.5M people" },
  { id: "48", title: "Berlin BVG Green Tram Tracks", sector: "Rail", measure: "Green tramways", hazards: ["Extreme heat", "Heavy rainfall"], hook: "22,000+ metres green track" },
  { id: "49", title: "Thames Water – SuDS", sector: "Highways", measure: "SuDS", hazards: ["Flooding", "Urban creep"], hook: "Geocellular + rain gardens" },
  { id: "50", title: "Panama Canal – Fresh Water Surcharge", sector: "Maritime", measure: "Fresh water surcharge", hazards: ["Drought"], hook: "Variable fee for water preservation" },
];

export const PLACEHOLDER_CASES: Record<string, CaseStudy> = {
  Rail: {
    id: "PH_RAIL",
    title: "Rail case study being curated",
    organisation: "HIVE editorial team",
    sector: "Rail",
    hook: "Full case study coming soon",
    placeholder: true,
    hazards: { cause: [], effect: [] },
    assets: [],
    measures: [],
    tags: [],
    location: "—",
    ukRegion: "—",
    year: "—",
    cost: "—",
    costBand: "—",
    summary:
      "This case study is currently being curated and verified by the HIVE editorial team. It will include full adaptation measures, cost data, and UK applicability assessment.",
    transferability: "—",
    transferabilityNote: "—",
    ukApplicability: [],
    insight: "—",
  },
  Aviation: {
    id: "PH_AVIATION",
    title: "Aviation case study being curated",
    organisation: "HIVE editorial team",
    sector: "Aviation",
    hook: "Full case study coming soon",
    placeholder: true,
    hazards: { cause: [], effect: [] },
    assets: [],
    measures: [],
    tags: [],
    location: "—",
    ukRegion: "—",
    year: "—",
    cost: "—",
    costBand: "—",
    summary:
      "This case study is currently being curated and verified by the HIVE editorial team. It will include full adaptation measures, cost data, and UK applicability assessment.",
    transferability: "—",
    transferabilityNote: "—",
    ukApplicability: [],
    insight: "—",
  },
  Maritime: {
    id: "PH_MARITIME",
    title: "Maritime & ports case study being curated",
    organisation: "HIVE editorial team",
    sector: "Maritime",
    hook: "Full case study coming soon",
    placeholder: true,
    hazards: { cause: [], effect: [] },
    assets: [],
    measures: [],
    tags: [],
    location: "—",
    ukRegion: "—",
    year: "—",
    cost: "—",
    costBand: "—",
    summary:
      "This case study is currently being curated and verified by the HIVE editorial team. It will include full adaptation measures, cost data, and UK applicability assessment.",
    transferability: "—",
    transferabilityNote: "—",
    ukApplicability: [],
    insight: "—",
  },
  Highways: {
    id: "PH_HIGHWAYS",
    title: "Highways case study being curated",
    organisation: "HIVE editorial team",
    sector: "Highways",
    hook: "Full case study coming soon",
    placeholder: true,
    hazards: { cause: [], effect: [] },
    assets: [],
    measures: [],
    tags: [],
    location: "—",
    ukRegion: "—",
    year: "—",
    cost: "—",
    costBand: "—",
    summary:
      "This case study is currently being curated and verified by the HIVE editorial team. It will include full adaptation measures, cost data, and UK applicability assessment.",
    transferability: "—",
    transferabilityNote: "—",
    ukApplicability: [],
    insight: "—",
  },
};

// Hand-curated rich entries (7 original) — used as enrichment overrides
const SEED_OVERRIDES: Record<string, Partial<CaseStudy>> = {
  ID_19: { title: "Phoenix Cool Pavement Programme", sector: "Highways", hook: "100+ miles treated · 6°C surface temp reduction · $4.8m annual", hazards: { cause: ["High temperatures", "Urban Heat Island effect"], effect: ["Road surface overheating", "Increased energy demand"] }, assets: ["Road pavement"], measures: ["CoolSeal reflective coating", "Pavement maintenance programme", "University monitoring partnership"], ukRegion: "Applicable to UK urban areas", cost: "USD $4.8m annual (£3.73m); initial pilot £2.33m", costBand: "£1m–£10m", summary: "Reflective CoolSeal coating applied to 100+ miles of residential roads to combat extreme urban heat island effect. The product increases road reflectivity by 30% and reduces surface temperatures by 6°C, integrated into existing pavement maintenance budgets.", transferability: "Medium", transferabilityNote: "Directly applicable to UK cities experiencing urban heat island intensification. London hotspots already 4.5°C warmer at night than rural surroundings. Heat-related deaths in London more than doubled in 2022. Currently limited to streets with ≤25mph speed limit due to skid resistance constraints.", ukApplicability: ["London urban roads", "Major UK city centres", "Transport for London managed streets", "Local authority highway maintenance programmes"], insight: "Cool pavement also extends road longevity by reducing thermal degradation — delivering avoided maintenance costs beyond the cooling benefit. Funded from existing pavement maintenance budgets, not additional climate spend.", tags: ["highways", "roads", "heat", "urban heat island", "heatwave", "pavement", "reflective coating", "surface temperature", "city"] },
  ID_40: { title: "Sheffield Grey to Green", sector: "Highways", hook: "60% grey to green · discharge cut 80% · 75,000 plants · 561% biodiversity uplift", hazards: { cause: ["Flooding – fluvial", "Flooding – surface water", "Heavy rainfall"], effect: ["Water damage", "Infrastructure disruption"] }, assets: ["Road pavement", "Foot and cycle paths", "Rail track", "Trams", "Bridges", "Signals and signalling", "Buildings and stations"], measures: ["Sustainable Drainage Systems (SuDS)", "Rain gardens", "Vegetated swales", "Nature-based solutions", "Green street corridor"], ukRegion: "Yorkshire & Humber", cost: "Phase 1 £3.6m; Phase 2 £6.3m; Phase 3 ongoing", costBand: "£1m–£10m per phase", summary: "1.5km urban green corridor replacing a former ring road dual carriageway with Sustainable Drainage Systems following the 2007 floods that caused £30m damage, killed 2 people, closed Sheffield station, cancelled tram services and damaged 28 roads.", transferability: "High", transferabilityNote: "UK case directly applicable nationwide. The largest retrofit grey-to-green project in the UK. Explicitly applicable to rail corridors following river valleys. Cross-sector impact — originally a road project that also protects rail and tram infrastructure downstream.", ukApplicability: ["UK city centre transport corridors", "Rail lines following river valleys", "Urban tram networks", "Local authority highway flood management"], insight: "SuDS reduced river discharge from a 1-in-100-year event by 87% — from 69.6 to 9.2 litres/sec. Inspired an £80m SuDS project in Mansfield. Now the default approach for Sheffield city centre regeneration.", tags: ["highways", "roads", "rail", "tram", "flooding", "surface water", "SuDS", "nature-based", "urban drainage", "heavy rainfall", "green infrastructure", "river valley", "urban flooding"] },
  ID_UKPN_01: { title: "Croydon Grid Flood Defence", sector: "Critical Infrastructure", hook: "69,000 customers protected · 1-in-1,000-year flood standard · £800k", hazards: { cause: ["Flooding – fluvial"], effect: ["Power disruption", "Loss of electricity supply to transport networks"] }, assets: ["Electrical substation", "Transformers", "Electrical buildings"], measures: ["Permanent flood barriers", "Equipment sealing", "Equipment elevation above flood level", "Flood walls around transformers"], ukRegion: "London & South East", cost: "£800,000 (this site); £14m total programme since 2010", costBand: "Under £1m (site); £10m–£100m (programme)", summary: "Permanent flood barriers installed at Croydon Grid substation to withstand a 1-in-1,000-year flood of the River Wandle, protecting electricity supply to 69,000 homes and businesses including transport infrastructure in South London.", transferability: "High", transferabilityNote: "Part of UK Power Networks' programme that has now protected 119 substations from river, tidal and surface water flooding. Highly relevant to substations supporting rail electrification infrastructure and EV charging networks across South East England.", ukApplicability: ["UK electrical substations in flood-risk zones", "Rail electrification supply infrastructure", "Urban transport power supply", "South East England energy grid"], insight: "Equipment sealing, raising above flood level, and targeted flood walling at a single site cost £800k — part of a £14m programme protecting 119 substations since 2010. Demonstrates that site-specific incremental hardening at modest cost delivers significant network resilience.", tags: ["energy", "flooding", "fluvial", "critical infrastructure", "substation", "power supply", "resilience", "flood barriers", "south london", "rail electrification"] },
  ID_32: { title: "Heathrow Airport Balancing Ponds", sector: "Aviation", hook: "Year-round flow control · £2.1m bundled into wider programme", hazards: { cause: ["Heavy rainfall", "Drought"], effect: ["Flooding – fluvial", "Flooding – surface water"] }, assets: ["Access routes", "Airport services"], measures: ["Balancing ponds", "Tilting weirs", "Nature-based solution", "MBBR wastewater treatment"], ukRegion: "London & South East", cost: "£2.1m (sheet piling component)", costBand: "£1m–£10m", summary: "Constructed balancing ponds to manage both drought and heavy rainfall events, controlling water volume entering drainage systems and reducing flood risk to airport access routes.", transferability: "High", transferabilityNote: "Tilting weir systems and Nature-based Solutions directly applicable to other airports, ports, and urban transport infrastructure facing surface water flooding.", ukApplicability: ["Other UK airports", "Urban transport hubs", "Coastal infrastructure"], insight: "Integrating climate adaptation into planned development activities kept costs minimal — bundled with a wider infrastructure programme rather than treated as standalone.", tags: ["aviation", "flooding", "drought", "nature-based", "urban drainage", "water management", "heavy rainfall", "surface water"] },
  ID_06: { title: "Austrian Federal Railways Climate Adaptation", sector: "Rail", hook: "212km barriers · 3,370ha protected forest · sensors across Alpine network", hazards: { cause: ["Heavy rainfall", "Storms", "Freeze-thaw cycles"], effect: ["Landslides", "Rockfalls", "Flooding – fluvial"] }, assets: ["Track", "Bridges", "Earthworks", "Signalling", "Level crossings"], measures: ["Slope stabilisation", "Rockfall barriers", "Flood retention basins", "Early warning systems", "Real-time geotechnical monitoring"], ukRegion: "Applicable UK-wide", cost: "Adaptation-specific costs not separately reported", costBand: "Large programme", summary: "Comprehensive physical and predictive technology adaptations across the Alpine rail network, combining slope stabilisation, protective barriers and geotechnical sensor monitoring.", transferability: "High", transferabilityNote: "Rockfall barriers, drainage management and slope stabilisation directly applicable to UK upland rail. Particularly relevant to the Peak District, Scottish Highlands, and Welsh valley lines.", ukApplicability: ["Wales", "UK upland rail", "Scottish Highlands lines", "Welsh Valley lines", "Peak District infrastructure"], insight: "Site-specific assessment — combining damage history, local conditions, and vulnerability analysis — was more effective than blanket solutions. Early warning systems reduced reactive maintenance costs significantly.", tags: ["rail", "landslide", "flooding", "sensors", "monitoring", "earthworks", "slope", "embankment", "precipitation", "rockfall", "freeze-thaw", "frost", "cold", "winter", "ice", "frozen ground"] },
  ID_01: { title: "Port of Calais Extension and Sea Defence", sector: "Maritime", hook: "3.3km seawall · 100-year design life · €863m total", hazards: { cause: ["Sea level rise", "Storms and high winds"], effect: ["Storm surge", "Coastal flooding", "Coastal erosion"] }, assets: ["Port structures", "Terminal", "Retaining walls"], measures: ["3.3km sea wall", "Land reclamation", "Reinforced retaining walls", "100-year design life specification"], ukRegion: "Applicable to UK coastal", cost: "€863m total project", costBand: "£100m+", summary: "Doubled port capacity while building a 3.3km seawall designed for 100-year service life, explicitly accounting for sea level rise and climate change projections in all structural specifications.", transferability: "High", transferabilityNote: "Directly applicable to UK ports facing sea level rise risk. Humber Ports specifically identified as having medium sea level rise risk.", ukApplicability: ["Humber Ports", "Port of Dover", "Thames Estuary infrastructure", "East coast ports"], insight: "Treating climate resilience as a core design requirement from the outset — not as an add-on — allowed the seawall to be cost-effectively integrated into a wider port upgrade.", tags: ["maritime", "ports", "sea level rise", "storm surge", "coastal", "flooding", "seawall", "infrastructure"], source_pdf_url: "https://trib.org.uk/documents/ID%2001_Port%20of%20Calais_Extension%20and%20sea%20defence.pdf" },
  ID_11: { title: "Deutsche Bahn Climate Adaptation Measures", sector: "Rail", hook: "25% storm damage reduction · 20% fewer heat disruptions · IoT across national network", hazards: { cause: ["High temperatures", "Storms and high winds"], effect: ["Vegetation dieback", "Storm damage", "Track overheating"] }, assets: ["Tracks", "Trains", "Overhead lines", "Lineside vegetation"], measures: ["Air-conditioned rolling stock (ICE 4)", "AI-assisted vegetation mapping", "IoT temperature sensors", "DB Climate Forest programme"], ukRegion: "Applicable UK-wide", cost: "€6bn (ICE 4 fleet); €625m (vegetation programme)", costBand: "Large programme", summary: "Phased adaptation combining air-conditioned rolling stock, AI-assisted vegetation management via satellite data, and IoT sensor networks to address escalating heat and storm risks.", transferability: "High", transferabilityNote: "Vegetation management and rolling stock air-conditioning directly applicable to UK rail. Highest priority in South and East England where temperatures are projected to reach higher peaks.", ukApplicability: ["Network Rail Southern region", "East Midlands Railway", "UK rolling stock procurement", "Lineside vegetation management"], insight: "Vegetation management delivered 25% reduction in storm damage between 2018 and 2020 — one of the highest ROI findings in the HIVE database. Heat disruptions fell 20% after ICE 4 deployment.", tags: ["rail", "heat", "temperature", "vegetation", "sensors", "rolling stock", "storms", "heatwave", "overheating"] },

  // ── Additional overrides to improve keyword retrieval for common query types ──

  ID_10: { title: "Infrabel Climate Adaptation Measures", sector: "Rail", hook: "Point heating prevents frozen switches · tension devices stop track fracturing · €500k saved in coldest week of 2022–23", hazards: { cause: ["High temperatures", "Freeze-thaw", "Heavy rainfall"], effect: ["Track buckling", "Track fracturing", "Frozen switches", "Flooding"] }, assets: ["Track", "Switches and points", "Earthworks", "Hydraulic structures"], measures: ["Tension release devices", "Automatic point heating systems", "Real-time weather monitoring stations", "Storm basins", "Embankment stability assessments"], ukRegion: "Applicable UK-wide", cost: "Not publicly reported; avoided costs estimated up to €2m per harsh winter", costBand: "Not reported", summary: "Belgium's national rail operator Infrabel implemented a suite of climate adaptation measures addressing both high and low temperature extremes: tension release devices prevent tracks buckling in summer heat and fracturing in winter cold; automated weather stations trigger point heating to prevent switch rails freezing; storm basins and embankment assessments address flooding risk.", transferability: "High", transferabilityNote: "Directly applicable to UK rail. Tension release devices and automated point heating are standard but under-deployed technologies. The weather station network feeding automatic controls is directly replicable on Network Rail's managed infrastructure.", ukApplicability: ["Network Rail switching infrastructure", "UK upland rail exposed to frost", "High-speed rail lines vulnerable to buckling", "Legacy rail infrastructure in cold regions"], insight: "Weather stations controlling automatic point heating saved 3.2 GWh and approximately €500,000 in the coldest week of winter 2022–23 alone — demonstrating that real-time monitoring pays back rapidly in avoided emergency maintenance costs.", tags: ["rail", "freeze-thaw", "frost", "cold", "winter", "low temperatures", "point heating", "track buckling", "track fracturing", "switches", "temperature monitoring", "sensors", "heat", "flooding", "embankment"] },

  ID_16: { title: "Network Rail Conwy Valley Resilience Measures", sector: "Rail", hook: "16,000 tonnes rock armour · culverts installed · embankment reinforcement", hazards: { cause: ["Heavy rainfall", "Storms and high winds", "Surface water flooding"], effect: ["Track washout", "Earthworks failure", "Service disruption"] }, assets: ["Track", "Earthworks", "Embankments", "Culverts", "Bridges"], measures: ["Rock armour installation", "Culvert construction", "Embankment reinforcement", "Drainage management"], ukRegion: "Wales", cost: "Not separately reported", costBand: "£1m–£10m", summary: "Following severe flooding incidents on the Conwy Valley railway line — located on a flood plain near the Conwy Estuary — Network Rail reinforced embankments with rock armour and installed culverts to protect the track from washouts and manage floodwaters effectively.", transferability: "High", transferabilityNote: "Directly applicable to UK rail lines in river valleys and flood-prone upland areas. The embankment and culvert interventions are standard techniques transferable across Network Rail routes.", ukApplicability: ["UK upland rail lines", "River valley rail corridors", "Network Rail flood-risk routes", "Welsh valley lines"], insight: "Drainage systems managed by Network Rail are critical for preventing flooding — significant financial impacts from weather-related incidents highlight the need for proactive resilience measures.", tags: ["rail", "flooding", "earthworks", "embankment", "slope", "rock armour", "culverts", "washout", "drainage", "river valley", "Wales", "fluvial flooding", "surface water"] },

  ID_31: { title: "Network Rail Drainage System Management", sector: "Rail", hook: "£2.8bn CP7 weather resilience · slope stabilisation · real-time condition monitoring", hazards: { cause: ["Heavy rainfall", "Flooding – fluvial", "Flooding – surface water"], effect: ["Water damage", "Slope failure", "Infrastructure disruption", "Service delays"] }, assets: ["Track", "Earthworks", "Slopes", "Embankments", "Drainage infrastructure"], measures: ["Slope stabilisation", "Drainage maintenance programme", "Remote condition monitoring (RCM)", "CCTV drainage surveys", "Landslip sensor networks"], ukRegion: "Applicable UK-wide", cost: "£2.8bn total Control Period 7 weather resilience programme", costBand: "£100m+", summary: "Network Rail's national drainage management programme highlights the critical role of proactive drainage maintenance in preventing flooding and slope failure across the rail network, with significant financial impacts from weather-related incidents driving investment in predictive monitoring.", transferability: "High", transferabilityNote: "Slope stabilisation, drainage maintenance and remote monitoring techniques directly applicable to highways earthworks and cutting slopes as well as rail infrastructure.", ukApplicability: ["Wales", "UK rail network earthworks", "Highway cutting slopes", "Network Rail managed routes", "High Speed 2 earthworks corridors"], insight: "Proactive slope stabilisation and drainage maintenance consistently delivers lower whole-life cost than reactive repair following failure. Remote condition monitoring reduces inspection frequency and improves early detection.", tags: ["rail", "slope stabilisation", "earthworks", "drainage", "landslip", "flooding", "embankment", "slope failure", "condition monitoring", "sensors", "infrastructure resilience"] },

  ID_42: { title: "Santa Barbara Randall Road Debris Basin", sector: "Highways", hook: "6-acre debris capture basin · Highway 101 corridor · Thomas Fire aftermath", hazards: { cause: ["Heavy rainfall", "Landslides", "Debris flows", "Wildfire aftermath"], effect: ["Highway closure", "Slope failure", "Debris inundation", "Road damage"] }, assets: ["Highway", "Road corridor", "Culverts", "Drainage infrastructure"], measures: ["Debris capture basin", "Catchment-scale drainage", "Slope stabilisation works", "Emergency road protection"], ukRegion: "Applicable to UK upland motorway corridors", cost: "Not reported", costBand: "£1m–£10m (estimated)", summary: "A 6-acre debris capture basin constructed on Randall Road to protect Highway 101 (US equivalent of a motorway) from landslides and debris flows triggered by the 2018 Thomas Fire and subsequent heavy rainfall in Santa Barbara County, California.", transferability: "Medium", transferabilityNote: "Debris basin approach directly applicable to UK motorways in upland or post-wildfire catchment areas experiencing slope instability. Particularly relevant to A-roads and motorways in Scottish Highlands, Welsh valleys, and the Pennines.", ukApplicability: ["Wales", "UK motorways in upland catchments", "A-roads adjacent to unstable slopes", "Post-wildfire road corridors", "Scottish Highland road network"], insight: "Catchment-scale debris management is more cost-effective than repeated reactive clearance following slope failures. Basin design must account for post-wildfire sediment yields which can be 10–100x normal levels.", tags: ["highways", "motorway", "road", "slope instability", "landslide", "debris flow", "slope failure", "highway protection", "geohazard", "catchment management", "wildfire", "rainfall-triggered failure"] },

  ID_46: { title: "Network Rail Dawlish Sea Wall", sector: "Rail", hook: "8m height recurve design · 120-year design life · coastal rail protection", hazards: { cause: ["Sea level rise", "Storms and high winds", "Wave overtopping", "Coastal erosion"], effect: ["Coastal flooding", "Storm surge", "Track damage", "Line closure"] }, assets: ["Sea wall", "Track", "Railway formation", "Coastal infrastructure"], measures: ["Sea wall reconstruction to 8m height", "Recurve wave return design", "Rock armour apron", "120-year design life specification"], ukRegion: "South West England", cost: "Approximately £80m (sea wall reconstruction)", costBand: "£10m–£100m", summary: "Reconstruction of the iconic Dawlish sea wall to protect the coastal rail line connecting South West England to the rest of the network, following catastrophic collapse in the 2014 storms. The new wall is designed for 120-year service life accounting for sea level rise.", transferability: "High", transferabilityNote: "Directly applicable to other coastal rail and road infrastructure at risk from wave overtopping and storm surge. Recurve design and high-specification design life are transferable to UK port structures and coastal highways.", ukApplicability: ["Coastal rail lines", "Coastal highways", "Port sea defences", "UK south-west coastal infrastructure"], insight: "Designing for a 120-year service life with sea level rise projections built in from the outset avoids costly retrofitting and protects a strategically critical transport link.", tags: ["rail", "coastal", "sea wall", "storm surge", "wave overtopping", "coastal flooding", "sea level rise", "storms", "coastal erosion", "maritime", "infrastructure protection"] },

  ID_79: { title: "Environment Agency Thames Tidal Flood Barrier", sector: "Maritime", hook: "520m barrier · 1.25M properties protected · tidal surge defence for London", hazards: { cause: ["Sea level rise", "Storm surge", "Tidal flooding"], effect: ["Tidal flooding", "Transport network disruption", "Urban flooding"] }, assets: ["Tidal barrier", "Flood defence infrastructure", "River infrastructure"], measures: ["Tidal surge barrier", "Operational flood gate management", "Predictive tidal surge forecasting"], ukRegion: "London & South East", cost: "£535m construction (1974–1982 prices)", costBand: "£100m+", summary: "The Thames Flood Barrier provides tidal surge protection for 1.25 million properties and critical transport infrastructure including the London Underground, rail, and road network. It has been raised over 200 times to protect against tidal surge events.", transferability: "Medium", transferabilityNote: "Tidal barrier approach applicable to other major estuarine ports and transport corridors. Operational management and forecasting model transferable to Humber, Severn, and Mersey estuaries.", ukApplicability: ["Estuarine port infrastructure", "Coastal and tidal transport corridors", "London transport network flood protection", "Humber and Severn estuary planning"], insight: "The barrier protects multiple transport modes simultaneously — Tube, rail, and road — demonstrating that large-scale tidal defences deliver systemic cross-sector resilience at scale.", tags: ["maritime", "tidal", "storm surge", "coastal flooding", "sea level rise", "flood barrier", "port", "estuarine", "transport resilience", "London"] },

  ID_02: { title: "Prince Edward Island Intertidal Reef Highway Protection", sector: "Highways", hook: "2,400 tonnes sandstone reefs · 45m offshore · Trans-Canada Highway protected", hazards: { cause: ["Sea level rise", "Storms and high winds"], effect: ["Coastal erosion", "Highway flooding", "Dune breach"] }, assets: ["Road pavement", "Coastal highway"], measures: ["Intertidal reef construction", "Dune restoration", "Shoreline stabilisation", "Adaptive management"], ukRegion: "Applicable to UK coastal", cost: "CAD $115,000 (approx. £67k); shared federal/provincial funding", costBand: "Under £1m", summary: "Two intertidal reefs totalling 2,400 tonnes of locally sourced sandstone were installed 45 metres offshore to protect the Trans-Canada Highway at Souris from sea level rise, storms and coastal erosion — the first intertidal reefs built on Prince Edward Island. The nature-based solution attenuates wave action and promotes beach-dune growth, providing adaptive capacity as sea levels rise.", transferability: "Medium", transferabilityNote: "Intertidal reef approach applicable to UK coastal road and rail infrastructure at risk from storm erosion and sea level rise. Requires appropriate coastal geology and adequate space for reef placement.", ukApplicability: ["UK coastal highways", "Coastal rail lines in erosion-risk zones", "Low-lying coastal transport corridors"], insight: "Nature-based reefs using locally sourced stone achieved beach protection at a fraction of the cost of traditional hard armour, while also improving biodiversity and avoiding the erosion acceleration typical of conventional sea walls.", tags: ["highways", "coastal", "sea level rise", "storms", "coastal erosion", "nature-based", "reefs", "dune restoration", "beach", "transport resilience", "highway protection"] },

  ID_03: { title: "Copenhagen Metro Climate-Proofed Design", sector: "Rail", hook: "€30m adaptation built into €3bn metro · elevated entrances · waterproof tunnels · pump systems", hazards: { cause: ["Heavy rainfall", "Sea level rise"], effect: ["Surface water flooding", "Tunnel inundation", "Service disruption"] }, assets: ["Track", "Signalling and telecommunications", "Buildings and stations", "Tunnels"], measures: ["Elevated station entrances", "Waterproof tunnel designs", "Improved drainage", "In-tunnel pump systems", "Waterproof equipment room doors"], ukRegion: "Applicable UK-wide", cost: "€30m adaptation cost within €3bn Cityringen project", costBand: "£10m–£100m", summary: "Copenhagen Metro's Cityringen line (opened 2019) integrated climate adaptation into the design from the outset — elevated station entrances, waterproof outer doors on equipment rooms, in-tunnel pump systems, and concrete walls up to 2.3m high protecting above-ground sections from coastal flooding. Prompted by the 2011 cloudburst that severely disrupted the city's transport network.", transferability: "High", transferabilityNote: "Directly applicable to London Underground new line extensions and tunnelled transport infrastructure. Many flood-proofing measures (elevated entrances, pumping capacity, waterproof equipment rooms) are also retrofittable to existing underground stations.", ukApplicability: ["London Underground new extensions", "HS2 underground stations", "Tunnelled road and rail infrastructure", "Coastal metro and rail stations"], insight: "Integrating climate adaptation at design stage cost an estimated €30m within a €3bn project (under 1% uplift), versus the far higher cost of post-event repair and retrofitting — Copenhagen's 2011 cloudburst, which triggered this project, caused infrastructure damage costing many times this figure.", tags: ["rail", "metro", "flooding", "surface water", "heavy rainfall", "sea level rise", "tunnel", "drainage", "pump", "waterproof", "underground", "SuDS", "urban flooding"] },

  ID_04: { title: "Albert Canal Archimedes Screw Pumping Stations", sector: "Maritime", hook: "€7–7.5m per lock · 3M kWh annual generation · 40M tonnes freight protected from drought", hazards: { cause: ["Drought"], effect: ["Low water levels", "Canal navigation disruption", "Economic loss from freight stoppage"] }, assets: ["Canal", "Locks", "Waterway infrastructure"], measures: ["Archimedes screw pumping stations", "Hydroelectric power generation", "Water level management", "Multi-use lock infrastructure"], ukRegion: "Applicable UK-wide", cost: "€7–7.5m per lock system (6 locks total)", costBand: "£10m–£100m", summary: "Six lock systems along Belgium's 80-mile Albert Canal were fitted with world-scale Archimedes screws that pump water back up the canal during drought-induced low flows (maintaining commercial navigation for 40 million tonnes of annual freight) and generate 3 million kWh of renewable electricity per year when water levels are high.", transferability: "Low", transferabilityNote: "Limited direct applicability to UK where commercial inland waterway freight volumes are much lower than European waterways. However, the combined pump/hydropower approach could be relevant where UK canal cross-catchment water transfer strategies are considered (e.g. Grand Union Canal).", ukApplicability: ["Grand Union Canal water transfer corridor", "UK inland waterways with commercial freight", "Combined water resource and transport infrastructure"], insight: "The screws generate more electricity than they consume and produce 3 million kWh annually — meaning the adaptation effectively pays for itself over time through energy revenue while also protecting freight operations.", tags: ["maritime", "inland waterways", "drought", "canal", "hydroelectric", "water management", "water level", "nature-based", "freight", "resilience"] },

  ID_07: { title: "MTA New York City Flood Resilience Programme", sector: "Rail", hook: "3,000+ flood barriers · under-river tunnel rehab · $5bn Sandy lesson · equipment elevated above flood levels", hazards: { cause: ["Sea level rise", "Heavy rainfall", "Storms and high winds"], effect: ["Water damage", "Storm surge", "Service disruption", "Equipment failure"] }, assets: ["Track", "Signalling and telecommunications", "Buildings and stations", "Tunnels", "Pump systems"], measures: ["Flex gates", "Marine doors", "Stop logs", "Under-river tunnel rehabilitation", "Equipment elevation", "Emergency generators", "Flood walls", "Enhanced drainage"], ukRegion: "Applicable UK-wide", cost: "USD $5bn+ total resilience investment; St George Terminal contracts $158m", costBand: "£100m+", summary: "Following Superstorm Sandy's USD $5bn damage to New York's transit network in 2012, MTA deployed over 3,000 flood protection devices at 31 stations, rehabilitated 11 under-river tunnels, elevated critical equipment, constructed flood walls around subway yards, and hardened facilities — a comprehensive post-event resilience upgrade across the world's largest metro system.", transferability: "High", transferabilityNote: "Specific products (flex gates, marine doors, stop logs, deployable barriers) are directly applicable to UK underground and surface rail infrastructure in flood-risk zones. The MTA's risk assessment methodology and asset-vulnerability mapping is transferable to Transport for London and Network Rail.", ukApplicability: ["London Underground flood-risk stations", "Network Rail coastal and estuarine stations", "Crossrail Elizabeth line flood protection", "Transport for London surface stations"], insight: "Sandy caused USD $5bn in damage — a single event that proved the business case for the entire subsequent resilience programme. Proactive barrier and tunnel rehabilitation investment prevents repair costs an order of magnitude higher.", tags: ["rail", "metro", "flooding", "coastal flooding", "sea level rise", "storm surge", "flood barriers", "tunnel", "underground", "New York", "Sandy", "equipment elevation", "drainage", "pump"] },

  ID_09: { title: "Avatiu Port Cook Islands Climate-Proofed Wharf", sector: "Maritime", hook: "50-year design life · wharf raised 0.5m with 0.5m further adaptive capacity · rock armour extended 92m", hazards: { cause: ["Sea level rise", "Storms and high winds"], effect: ["Coastal erosion", "Storm surge", "Port structural failure"] }, assets: ["Port structures", "Port services", "Breakwater"], measures: ["Wharf height increase", "Rock armour breakwater extension", "Raised mooring bollards", "Adaptive fendering system", "Harbour dredging"], ukRegion: "Applicable to UK coastal", cost: "US $24.6m (£16.1m); 84% ADB financed", costBand: "£10m–£100m", summary: "Avatiu Port on Rarotonga, Cook Islands — handling 90% of the island's food imports — was rebuilt with a 50-year climate-resilient design: wharf deck raised 0.5m with capacity for a further 0.5m uplift as sea levels rise, rock armour breakwater extended 92m, and fendering systems designed for height adjustment. Avoided an estimated NZ$20m in emergency repair costs.", transferability: "Medium", transferabilityNote: "Adaptive port design principles (designing for incremental height increases as sea levels rise, flexible fendering systems) are directly applicable to UK coastal ports and harbour infrastructure.", ukApplicability: ["UK island and remote community ports", "Coastal port infrastructure facing sea level rise", "Associated British Ports managed facilities"], insight: "Building in adaptive capacity (the ability to raise the wharf a further 0.5m) at design stage costs marginally more but eliminates the need for a full rebuild as sea levels rise — a key design principle for long-lived coastal infrastructure.", tags: ["maritime", "ports", "sea level rise", "storms", "coastal", "storm surge", "wharf", "rock armour", "breakwater", "coastal erosion", "island infrastructure"] },

  ID_12: { title: "Leeds Flood Alleviation Scheme", sector: "Highways", hook: "£200m investment · 500,000 trees · moveable weirs (UK first) · 1-in-200-year protection to 2069", hazards: { cause: ["Heavy rainfall", "Flooding – fluvial"], effect: ["Water damage", "Infrastructure disruption", "Service delays"] }, assets: ["Buildings and stations", "Rail track", "Road pavement", "River infrastructure"], measures: ["Moveable weirs", "Flood walls and embankments", "Flood storage reservoir (1.8M m³)", "Natural Flood Management (NFM)", "500,000 trees over 1,240 hectares"], ukRegion: "Yorkshire & Humber", cost: "£200m (Phase 1 £50m; Phase 2 £150m+)", costBand: "£100m+", summary: "The Leeds Flood Alleviation Scheme provides 1-in-200-year flood protection for Leeds city centre and its rail and road network, combining moveable weirs (a UK first), 4.5km of flood walls, a 1.8 million m³ flood storage reservoir, and the UK's first catchment-scale Natural Flood Management programme with 500,000 trees planted upstream. Storm Eva in 2015 caused £500m in recovery costs — the business case for Phase 2.", transferability: "High", transferabilityNote: "The moveable weir approach, catchment-scale NFM, and partnership funding model are all directly replicable by UK local authorities and Environment Agency in other flood-risk river cities. NFM is especially relevant where railway lines follow river valleys.", ukApplicability: ["UK river city transport corridors", "Rail lines following river valleys", "Yorkshire and northern England flood-risk networks", "Local authority and Network Rail partnership schemes"], insight: "Moveable weirs have been activated 9 times since 2017. The NFM element is forecast to reduce peak flow in Leeds by 5.6% — demonstrating that nature-based upstream interventions deliver measurable downstream protection at city scale.", tags: ["highways", "roads", "rail", "flooding", "fluvial flooding", "heavy rainfall", "flood walls", "weirs", "nature-based", "SuDS", "NFM", "river valley", "Yorkshire", "UK"] },

  ID_13: { title: "Transport for London Marylebone Flyover Rain Gardens", sector: "Highways", hook: "3,500m² SuDS · largest sustainable drainage system in central London · £1.7m construction", hazards: { cause: ["Heavy rainfall"], effect: ["Surface water flooding", "Combined sewer overload"] }, assets: ["Road pavement"], measures: ["Rain gardens (bioretention)", "Sustainable Drainage Systems (SuDS)", "Silt traps", "Street tree planting"], ukRegion: "London & South East", cost: "£729k design fees; £1.7m construction; £1m GLA Green Infrastructure Fund grant", costBand: "£1m–£10m", summary: "Nine rain gardens (bioretention areas) were installed on the A5/A40 Marylebone flyover intersection in central London, repurposing a disused subway station to create 3,500m² of SuDS — the largest sustainable drainage system in central London. Completed 2024, the scheme handles storms from 1-in-5 to 1-in-20 years, with no flooding in surrounding streets recorded since installation.", transferability: "High", transferabilityNote: "Directly applicable to UK urban road junctions experiencing surface water flooding where disused underground or sub-surface infrastructure can be repurposed. The retrofit SuDS model minimised road disruption — a key benefit for busy urban highways.", ukApplicability: ["London urban road junctions", "Other UK city centre SuDS retrofit opportunities", "TfL and local highway authority road networks", "Urban rail and road station approaches"], insight: "TfL met 70% of its 2024 annual SuDS installation target from this single project. Repurposing existing disused space (subway ramps/stairs) eliminated the need for costly deep excavation in a busy central London carriageway.", tags: ["highways", "roads", "flooding", "surface water", "heavy rainfall", "SuDS", "rain gardens", "drainage", "urban flooding", "London", "TfL", "nature-based", "UK"] },

  ID_14: { title: "Adelaide Airport Irrigation Cooling Trial", sector: "Aviation", hook: "3°C air temperature reduction · stormwater reuse · $1M+ annual airline fuel savings modelled", hazards: { cause: ["High temperatures"], effect: ["Aircraft load reduction", "Dust generation", "Vegetation dieback"] }, assets: ["Airport services", "Airfield grass zones"], measures: ["Stormwater irrigation", "Lucerne crop cultivation", "Air temperature monitoring", "Aquifer storage and recovery"], ukRegion: "Applicable UK-wide", cost: "Trial cost: $52k capital; $2.4m for full 200ha scale-up", costBand: "Under £1m (trial)", summary: "Adelaide Airport trialled stormwater irrigation of a 4-hectare airside area using an adjacent aquifer storage system, producing a greater than 3°C air temperature reduction on hot days compared to unirrigated areas. Projected at 200ha scale, airlines could save over $1m annually from maintained payloads and fuel savings during take-off and landing. Lucerne crop grown for additional revenue.", transferability: "Low", transferabilityNote: "Applicable to UK airports in southern England facing increasing summer heatwave risks, particularly where stormwater storage infrastructure already exists. Dependent on land availability, water source access, and aviation safety compliance (bird strike management).", ukApplicability: ["Heathrow Airport airside zones", "Gatwick Airport airfield areas", "UK regional airports with airside grassland"], insight: "The trial showed that irrigation cools surface temperatures as effectively as pavement — demonstrating that maintaining vegetation cover at airports delivers both operational and temperature-reduction benefits at far lower cost than hard engineering interventions.", tags: ["aviation", "heat", "high temperatures", "urban heat island", "irrigation", "airfield", "cooling", "nature-based", "water management", "temperature monitoring"] },

  ID_15: { title: "Environment Agency Clays Lake Flood Storage Reservoir (Gatwick)", sector: "Aviation", hook: "400,000m³ capacity · 280+ homes and Gatwick Airport protected · 1-in-10,000-year dam design", hazards: { cause: ["Flooding – fluvial", "Flooding – surface water", "Storms and high winds"], effect: ["Water damage", "Airport operational disruption", "Service cancellations"] }, assets: ["Mechanical and electrical equipment", "Buildings and stations", "Airport services", "Airfield"], measures: ["Flood storage reservoir (dam)", "Catchment flood risk management", "Leaky dams and nature-based upstream interventions"], ukRegion: "London & South East", cost: "£4m Gatwick contribution; £17m total Upper Mole scheme (4 reservoirs)", costBand: "£10m–£100m", summary: "The Clays Lake Scheme — one of four flood storage reservoirs in the Upper Mole Flood Alleviation Scheme — increased a lake's capacity from 10,000m³ to nearly 400,000m³, providing 1-in-50-year fluvial flood protection to Gatwick Airport, over 280 homes, and key road infrastructure. The 2013–14 storms, which caused 145 Gatwick flight cancellations and disrupted 13,000 passengers, directly drove this investment.", transferability: "High", transferabilityNote: "Flood storage reservoir approach at catchment scale is directly applicable to UK airports and transport hubs in flood-prone river catchments. Nature-based upstream interventions (leaky dams, peatland restoration) provide complementary benefits.", ukApplicability: ["UK airports in flood-risk catchments", "Transport hubs adjacent to rivers", "London and South East transport infrastructure"], insight: "Gatwick's £4m contribution to the scheme (protecting a fraction of what a single disrupted Christmas Eve cost in 2013) demonstrates the cost-effectiveness of catchment-scale flood storage over site-specific flood barriers.", tags: ["aviation", "flooding", "fluvial flooding", "surface water", "heavy rainfall", "storm", "flood reservoir", "dam", "catchment", "airport", "Gatwick", "nature-based", "UK"] },

  ID_20: { title: "Victoria GFRP Bridge Reinforcement (Pound Road West)", sector: "Highways", hook: "100-year design life vs 30-year steel · 28% lower embodied carbon · corrosion-free bridge reinforcement", hazards: { cause: ["Heavy rainfall", "High temperatures"], effect: ["Steel corrosion", "Concrete spalling", "Infrastructure deterioration"] }, assets: ["Bridge", "Road pavement", "Shared user paths"], measures: ["Glass Fibre Reinforced Polymer (GFRP) rebar", "Corrosion-resistant bridge panels", "GFRP-reinforced shared path"], ukRegion: "Applicable UK-wide", cost: "AU$33k for GFRP component; AU$100–150m total project contract", costBand: "Under £1m (GFRP component)", summary: "Over 1,000 GFRP rebar bars replaced conventional steel in a new bridge's retaining walls and a 6km shared path in Victoria, Australia. Unlike steel (30-year lifespan before corrosion-related deterioration), GFRP is non-corrosive with 100+ year design life — directly relevant to UK coastal and road environments where de-icing salts and humidity accelerate steel degradation.", transferability: "High", transferabilityNote: "GFRP rebar is directly applicable to UK bridges, coastal highways, tunnels and road infrastructure where corrosion is the primary long-term maintenance cost driver. Particularly relevant in coastal splash zones and areas with heavy winter de-icing salt use.", ukApplicability: ["UK coastal highway bridges", "Motorway bridges subject to de-icing salt", "Rail and road tunnels", "Flood-exposed bridge abutments"], insight: "While GFRP has slightly higher upfront material cost, it eliminates the dominant lifecycle cost of steel infrastructure — corrosion repair. In Australia, corrosion of steel reinforcement costs AU$13bn annually.", tags: ["highways", "roads", "bridges", "corrosion", "flooding", "heavy rainfall", "high temperatures", "climate resilience", "materials", "maintenance", "lifecycle", "coastal"] },

  ID_21: { title: "Heysen Tunnels Fire Safety and Ventilation Upgrade (South Australia)", sector: "Highways", hook: "23 exhaust fans · automated fire suppression · AUD$150m upgrade · wildfire tunnel safety", hazards: { cause: ["High temperatures"], effect: ["Wildfire", "Air pollution", "Tunnel fire risk"] }, assets: ["Road pavement", "Tunnels", "Traffic management systems"], measures: ["Exhaust ventilation fans (23 new)", "Automated fire suppression (2hr spray capacity)", "Emergency communications system", "Intelligent transport system upgrades", "Thermal incident detection"], ukRegion: "Applicable UK-wide", cost: "AUD $150m (combined Australian and South Australian Government)", costBand: "£100m+", summary: "Major safety refit of the Heysen Tunnels on South Australia's South Eastern Freeway, driven by increasing wildfire and extreme heat risk: 23 new exhaust fans to disperse smoke, automated fire suppression capable of spraying water for two hours, and upgraded ITS including thermal incident detection. The fire safety standard achieved is described by the infrastructure authority as 'the safest tunnels anywhere in the world'.", transferability: "Medium", transferabilityNote: "The tunnel ventilation and fire suppression approach is applicable to UK road tunnels as wildfire risk increases, particularly in upland and moorland road corridors. The UK has no dedicated tunnel fire suppression standard — this case provides evidence for raising requirements.", ukApplicability: ["Major UK road tunnels", "Upland road corridors with wildfire exposure", "Scottish Highland tunnels and roads"], insight: "Wildfire in UK is an emerging but rapidly growing risk (2022 London grass fires, 2019 Sutherland peatland fires). This case demonstrates that tunnel fire suppression systems are technically proven and deployable at reasonable cost relative to the risk they mitigate.", tags: ["highways", "roads", "tunnels", "wildfire", "fire", "high temperatures", "ventilation", "safety", "ITS", "smoke", "emergency"] },

  ID_22: { title: "Parramatta Cool Roads Trial (Western Sydney)", sector: "Highways", hook: "14,700m² treated across 12 sites · 6°C surface cooling · urban heat island mitigation", hazards: { cause: ["High temperatures"], effect: ["Urban Heat Island effect", "Heat stress"] }, assets: ["Road pavement"], measures: ["CoolSeal reflective pavement coating", "Surface temperature monitoring", "Environmental monitoring programme"], ukRegion: "Applicable to UK urban areas", cost: "AU$15m application cost (at trial scale; significantly lower at Phoenix/city scale)", costBand: "£1m–£10m", summary: "A 2019–21 trial applied CoolSeal reflective coating to 14,700m² of road across 12 sites in three Western Sydney councils, achieving 6°C surface temperature reductions on hot summer days. Confirmed surface cooling benefits but found no systematic reduction in ambient air temperature — useful counter-evidence to complement ID_19 (Phoenix, which found greater success at larger deployment scale).", transferability: "Medium", transferabilityNote: "Applicable to UK cities experiencing urban heat island intensification in summer heatwaves. This trial provides both the evidence for surface cooling and important caveats on scale thresholds — effective at city scale, not at trial-patch scale. Read alongside ID_19 (Phoenix) for the full picture.", ukApplicability: ["London urban roads and boroughs", "Major UK city urban heat island hotspots", "TfL and local highway authority programmes"], insight: "CoolSeal reduced surface temperatures by 6°C but did not reduce ambient air temperature at trial scale — suggesting city-scale deployment (as in Phoenix, ID_19) is needed for air temperature effects. A companion case study to ID_19.", tags: ["highways", "roads", "heat", "high temperatures", "urban heat island", "cool pavement", "reflective coating", "urban cooling", "surface temperature", "heatwave"] },

  ID_23: { title: "LA Metro Climate Action and Adaptation Plan", sector: "Rail", hook: "Spring tensioners prevent wire sag at 45°C · landslide barrier walls · Rory Shaw Wetlands Park", hazards: { cause: ["High temperatures", "Heavy rainfall", "Flooding – surface water"], effect: ["Landslides", "Water damage", "Overhead wire sag", "Wildfire", "Service disruption"] }, assets: ["Track", "Overhead lines", "Stations", "Buses and BRT"], measures: ["Overhead catenary spring tensioner upgrades (27.2 miles)", "Landslide barrier wall", "Wetland park for stormwater", "Blue water bus detour protocols", "Infrastructure elevation in flood zones"], ukRegion: "Applicable UK-wide", cost: "$10.7m OCS upgrade; Green Bonds total $890m+", costBand: "£1m–£10m (OCS)·£100m+ (programme)", summary: "LA Metro's climate adaptation plan addresses multiple simultaneous hazards: spring tensioners replace traditional balance weights on 27.2 miles of overhead catenary to prevent high-heat sag and dewirements; a barrier wall protects tracks from an ongoing San Clemente landslide (closed 5 times in 3 years); a 46-acre wetland park manages stormwater while providing public recreation. Green Bonds finance the programme.", transferability: "Medium", transferabilityNote: "Overhead catenary spring tensioner upgrade (replacing balance weights) is directly applicable to UK light rail and tram networks experiencing heat-related sag on overhead lines. Integrated stormwater/wetland approach applicable to transport corridor land management.", ukApplicability: ["UK light rail and tram networks", "Network Rail OLE in high-heat corridors", "Urban transit corridor stormwater management"], insight: "Moving from balance weights to spring tensioners on overhead lines is a low-cost mechanical change that eliminates heat-related dewirements — a transferable fix for UK tram and light rail systems experiencing increasing summer temperature extremes.", tags: ["rail", "light rail", "overhead lines", "heat", "high temperatures", "landslide", "flooding", "wildfire", "OLE", "catenary", "urban flooding", "nature-based", "SuDS", "tram"] },

  ID_25: { title: "Dania Beach Florida Coastal Drainage Resilience", sector: "Maritime", hook: "Submersible lift stations · stormwater master plan · sea level rise adaptation for coastal roads and port", hazards: { cause: ["Sea level rise", "Storms and high winds"], effect: ["Water damage", "Storm damage", "Drainage overload"] }, assets: ["Roads", "Buildings and warehouses", "Port structures"], measures: ["Submersible lift station replacements", "Emergency generator upgrades", "Stormwater pipe and catch basin installation", "Flood-resistant road resurfacing", "Stormwater Master Plan"], ukRegion: "Applicable to UK coastal", cost: "$8.34m (lift stations); $2.51m (stormwater improvements)", costBand: "£1m–£10m", summary: "Dania Beach (pop. 32,000), a low-lying coastal Florida community, upgraded wastewater lift stations to sealed submersible systems with emergency generators, installed stormwater drainage infrastructure, and is developing a citywide Stormwater Master Plan — all under Florida's Resilient Florida Program. Cumulative sea level rise damage projected at $1.17bn from 2030–2070 without adaptation.", transferability: "Medium", transferabilityNote: "Submersible lift station upgrades and stormwater master planning approach are applicable to UK coastal and estuarine urban areas facing combined sea level rise and surface water flooding risk. Southeast Coast, East Coast and Southwest Coast UK areas have highest applicability.", ukApplicability: ["UK coastal town road networks", "Low-lying coastal port infrastructure", "UK estuarine urban drainage systems"], insight: "Flood-resilient submersible pumps remain operational while submerged — a critical resilience property for low-lying coastal areas where conventional pumps would fail exactly when most needed during a surge event.", tags: ["maritime", "roads", "coastal", "sea level rise", "storms", "flooding", "drainage", "SuDS", "coastal resilience", "pump stations", "stormwater"] },

  ID_26: { title: "Qatar Musaimeer Pumping Station and Outfall Tunnel", sector: "Maritime", hook: "19.7m³/s pumping capacity · 10km under-seabed outfall tunnel · protects Hamad International Airport", hazards: { cause: ["Heavy rainfall", "Flooding – surface water"], effect: ["Water damage", "Road pavement damage", "Rail track damage", "Airport disruption"] }, assets: ["Airport services", "Highways", "Rail track"], measures: ["Underground pumping station (19.7m³/s)", "10km under-seabed outfall tunnel (3.7m diameter)", "1-in-50-year storm design standard"], ukRegion: "Applicable UK-wide", cost: "£219m construction; £2.6m annual operation and maintenance", costBand: "£100m+", summary: "Qatar's Musaimeer Pumping Station and Outfall collects stormwater and groundwater from a 270km² catchment around Doha, pumping it via a 10km sub-seabed tunnel to prevent flooding of Hamad International Airport and surrounding roads. Designed for a 1-in-50-year storm event. Achieved CEEQUAL 'Very Good' rating and 31% embodied carbon reduction. Successfully managed a November 2023 storm within design capacity.", transferability: "Low", transferabilityNote: "The large-scale pumping station and outfall approach is applicable to large UK transport hubs in flat, low-lying areas vulnerable to surface water ponding. The construction methodology (minimising land acquisition, sustainable spoil reuse) offers transferable project delivery lessons.", ukApplicability: ["UK airport drainage catchments", "Low-lying urban transport interchange flood protection", "Major coastal and estuarine infrastructure"], insight: "100% of dredged marine material was reused for land reclamation, and £2.5m was saved by reusing 450,000 tonnes of tunnel spoil — demonstrating that large-scale flood infrastructure can achieve high sustainability ratings through material reuse.", tags: ["aviation", "maritime", "highways", "flooding", "surface water", "heavy rainfall", "pumping station", "tunnel", "stormwater", "airport", "drainage", "large-scale infrastructure"] },

  ID_28: { title: "Sydney Metro North West Tunnel Ventilation System", sector: "Rail", hook: "100-year design life · 17 compressed air systems · heat-resistant track exhaust (300°C rated fans)", hazards: { cause: ["High temperatures"], effect: ["Passenger discomfort", "Fire risk", "Service disruption"] }, assets: ["Rail track", "Tunnels", "Stations"], measures: ["Tunnel axial ventilation fans", "Over-track exhaust systems", "17 compressed air systems", "100-year climate-risk design horizon"], ukRegion: "Applicable UK-wide", cost: "Embedded in £5.7bn total project; adaptation cost not separately reported", costBand: "Not reported", summary: "Sydney Metro North West (opened 2019) integrated climate resilience into tunnel design from the outset, modelling risks to 2100. Tunnel ventilation fans designed to withstand 300°C for two hours in fire scenarios also serve as primary heat management for passenger comfort during heatwaves. The line achieved 99%+ service reliability and 98% customer satisfaction over its first five years.", transferability: "High", transferabilityNote: "Directly applicable to UK new underground metro and rail tunnels. Most applicable to new-build design — retrofitting tunnel ventilation is significantly more expensive. Provides a design-specification benchmark for HS2 underground sections and future Crossrail extensions.", ukApplicability: ["HS2 underground sections", "London Underground new line proposals", "Future UK metro systems", "Tunnelled rail infrastructure"], insight: "Designing ventilation for a 100-year climate horizon at project outset costs a fraction of retrofitting — and the ventilation system doubles as fire safety infrastructure, delivering two resilience functions from one investment.", tags: ["rail", "metro", "tunnel", "heat", "high temperatures", "ventilation", "underground", "climate design", "passenger comfort", "fire safety", "heatwave"] },

  ID_30: { title: "Bradford Council ArborFlow SuDS Tree Pits", sector: "Highways", hook: "6 Field Maples · 30.81m³ storage · handles 1-in-30-year storm surge · Yorkshire Water sewer relief", hazards: { cause: ["Heavy rainfall", "Flooding – surface water"], effect: ["Sewer surcharge", "Surface water flooding", "Road flooding"] }, assets: ["Road pavement", "Drainage infrastructure"], measures: ["ArborFlow SuDS tree pits", "Stormwater attenuation and filtration", "Urban tree planting", "Combined sewer relief"], ukRegion: "Yorkshire & Humber", cost: "Not publicly reported; low-cost urban tree-pit system", costBand: "Under £1m", summary: "Six Field Maple trees with large-volume ArborFlow tree pits were installed on North Street, Keighley to relieve pressure on Yorkshire Water's combined sewer during storm events. The joint system stores 30.81m³ and accommodates peak rainfall for 3.5 hours during a 1-in-30-year storm. Post-installation monitoring confirmed strong tree vigour, effective pollutant filtration, and no major maintenance requirement.", transferability: "High", transferabilityNote: "Directly applicable across UK urban road networks experiencing surface water flooding. Particularly relevant for local highway authorities seeking low-cost, low-maintenance SuDS solutions that can be integrated with road alterations. Field Maples confirmed as effective species for this application.", ukApplicability: ["UK urban roads with surface water flooding", "Local authority highway flood management", "Northern England road networks", "Urban drainage relief alongside Yorkshire Water infrastructure"], insight: "ArborFlow tree pits are estimated to handle a 1-in-30-year storm with no significant maintenance — effectively delivering flood protection as a side-effect of routine street tree planting, at a fraction of the cost of drainage infrastructure upgrades.", tags: ["highways", "roads", "flooding", "surface water", "heavy rainfall", "SuDS", "drainage", "nature-based", "trees", "urban drainage", "Yorkshire", "UK", "Bradford"] },

  ID_33: { title: "Heathrow Airport Climate-Resilient Grass Standards", sector: "Aviation", hook: "Drought-tolerant fescue + ryegrass mix · 8.96 tCO2eq/ha carbon sequestration · 2024 deployment", hazards: { cause: ["High temperatures", "Drought"], effect: ["Vegetation dieback", "Dust generation", "Bird strike risk increase", "Fire hazard"] }, assets: ["Airport services", "Airfield grass zones"], measures: ["Climate-resilient grass species (rhizomatous tall fescue + tetraploid perennial ryegrass)", "Species selection for deep root systems", "Planned gradual airfield resurfacing over 5–6 years"], ukRegion: "London & South East", cost: "Integrated into ongoing maintenance programme; initial capital not separately reported", costBand: "Under £1m", summary: "Following Heathrow's 2020 heatwave (37.8°C) and 2022 record (40.2°C) which killed much of the airfield's grass — creating dust, fire hazard and bird strike risks — Heathrow adopted a deep-rooted fescue/ryegrass mix bred for drought, heat, cold, disease and salt tolerance. Replacing existing grass species over 5–6 years within routine maintenance budgets. Sequesters 8.96 tCO2eq/ha as a co-benefit.", transferability: "High", transferabilityNote: "Directly applicable to UK airports, and to rail and highway earthwork embankments where vegetation loss under heatwave or drought conditions creates erosion, dust and safety risks. Species selection and root depth are the key variables for any open-ground transport asset.", ukApplicability: ["UK airports' airside grass management", "Rail embankment vegetation management", "Highway cutting and embankment slopes", "Southern England transport green spaces"], insight: "Grass die-off at Heathrow in 2020 created operational disruptions (dust, bird strike, fire risk) that would have cost far more than the grass replacement programme. Proactive species switching ahead of the next heatwave is a low-cost, high-certainty adaptation.", tags: ["aviation", "heat", "high temperatures", "drought", "vegetation", "grass", "airfield", "bird strike", "fire risk", "nature-based", "airport", "UK", "Heathrow"] },

  ID_34: { title: "Caltrans Gleason Beach Roadway Realignment", sector: "Highways", hook: "Highway 1 relocated 150m inland · 476m bridge over coastal gully · habitat restoration", hazards: { cause: ["Coastal flooding", "Storms and high winds"], effect: ["Coastal erosion", "Road damage", "Highway closure"] }, assets: ["Road pavement", "Bridges", "Coastal highway"], measures: ["Highway realignment (150m inland)", "New bridge construction (476m)", "Habitat restoration", "Nature-based coastal management"], ukRegion: "Applicable to UK coastal", cost: "Not reported in data available", costBand: "£10m–£100m (estimated)", summary: "A 1.5km section of California's iconic Highway 1 was permanently realigned 150m inland at Gleason Beach in Sonoma County, where continuing coastal erosion had left the road at imminent risk of collapse into the Pacific Ocean. A new 476m bridge spans the coastal gully. The project included habitat restoration of the vacated highway alignment, converting former pavement to coastal habitat.", transferability: "Medium", transferabilityNote: "Road realignment away from eroding coastlines is applicable to UK coastal highway routes (A-roads and B-roads) where continued maintenance of existing alignments becomes uneconomic due to accelerating coastal erosion. The bridge-over-gully approach is transferable to coastal landslide zones.", ukApplicability: ["UK coastal A-roads threatened by erosion", "SW England coastal road corridors", "Yorkshire and Scottish coastal transport routes"], insight: "Sometimes the most cost-effective adaptation is strategic retreat — permanently moving infrastructure inland is a one-time capital cost versus indefinite maintenance and emergency repair costs as a coastal road erodes.", tags: ["highways", "coastal", "coastal erosion", "storms", "sea level rise", "road relocation", "bridge", "coastal flooding", "highway protection", "nature-based", "habitat restoration"] },

  ID_37: { title: "Panama Canal Drought Water-Saving Measures", sector: "Maritime", hook: "Water-savings basins recover 60% of lockage water · fresh water surcharge introduced 2023 · shipping restrictions under drought", hazards: { cause: ["Drought"], effect: ["Low water levels", "Canal navigation restriction", "Global shipping disruption"] }, assets: ["Canal", "Locks", "Port structures"], measures: ["Water-savings basins in locks (60% water recovery)", "Cross-filling between lock chambers", "Fresh water surcharge for high-draught vessels", "Draft and transit restrictions"], ukRegion: "Applicable UK-wide", cost: "Not separately reported; operational measures and existing infrastructure adaptations", costBand: "Not reported", summary: "Severe 2023 drought reduced Panama Canal reservoir levels to near-record lows, forcing the Panama Canal Authority to restrict daily transits from 36–38 to 24 and limit vessel draft — disrupting global shipping. Water-savings basins (capturing 60% of lockage water for reuse), cross-filling protocols, and a new fresh water surcharge were activated to manage reduced water availability while maintaining canal viability.", transferability: "Low", transferabilityNote: "Limited direct UK transport applicability. The water-savings basin technology and drought management protocols are of interest to UK inland waterway operators (Canal & River Trust) and water resource planners facing combined transport and water supply challenges.", ukApplicability: ["Canal and River Trust inland waterway management", "UK water resource and transport planning intersection", "Estuarine and tidal barrage operations"], insight: "The Panama Canal crisis demonstrated that a single weather event (drought) can simultaneously trigger a global supply chain disruption — showing the systemic nature of climate risk in transport infrastructure beyond the asset itself.", tags: ["maritime", "canal", "drought", "water management", "inland waterways", "shipping", "low water", "water saving", "locks", "global supply chain"] },

  ID_39: { title: "Thames Water Counters Creek SuDS (London)", sector: "Highways", hook: "1,000+ properties protected · combined sewer relief in Kensington, Chelsea and Hammersmith", hazards: { cause: ["Heavy rainfall", "Flooding – surface water"], effect: ["Combined sewer surcharge", "Surface water flooding", "Property flooding"] }, assets: ["Road pavement", "Drainage infrastructure"], measures: ["Sustainable Drainage Systems (SuDS)", "Surface water attenuation", "Combined sewer relief measures", "Permeable paving"], ukRegion: "London & South East", cost: "Not publicly available", costBand: "Not reported", summary: "Thames Water implemented a SuDS programme in the Counters Creek catchment (Royal Borough of Kensington and Chelsea / London Borough of Hammersmith and Fulham) to address repeated surface water flooding from overwhelmed combined sewers following intense rainfall events. The area lost nearly 20% of permeable green space between 1971 and 2007, significantly increasing runoff. The scheme protects over 1,000 properties.", transferability: "High", transferabilityNote: "Directly applicable to UK urban areas with combined sewerage systems and high rates of historic paving-over of gardens and verges. The SuDS retrofit approach — adding attenuation to existing urban road and drainage infrastructure — is replicable across UK cities experiencing increased rainfall intensity.", ukApplicability: ["Urban London road and drainage networks", "Other UK cities with combined sewer systems", "Local authority surface water management plans"], insight: "The Counters Creek area lost 20% of permeable surface between 1971 and 2007 — showing that urban creep (garden paving, development) is a compounding factor alongside climate change in driving urban flood risk. SuDS addresses both simultaneously.", tags: ["highways", "roads", "flooding", "surface water", "heavy rainfall", "SuDS", "drainage", "urban flooding", "London", "UK", "combined sewer", "Thames Water"] },

  ID_51: { title: "Transport for London New Cross Gate Rainwater Harvesting", sector: "Rail", hook: "Depot-scale rainwater harvesting · reduced surface water runoff · sewer network pressure relief", hazards: { cause: ["Heavy rainfall", "Flooding – surface water"], effect: ["Surface water flooding", "Drainage overload"] }, assets: ["Rail depot", "Drainage infrastructure"], measures: ["Rainwater harvesting system", "Surface water runoff reduction", "Combined sewer relief"], ukRegion: "London & South East", cost: "Not publicly available", costBand: "Not reported", summary: "Transport for London installed a rainwater harvesting system at New Cross Gate Depot (London Overground maintenance and stabling facility) to capture and reuse roof runoff, reducing pressure on local combined sewer infrastructure during heavy rainfall events and mitigating the risk of surface water flooding to the depot and surrounding urban area.", transferability: "High", transferabilityNote: "Directly applicable to UK rail depots, stations, and maintenance facilities with large roof areas. Rainwater harvesting reduces both flood risk and mains water consumption — dual benefit particularly valuable for large transport sites with significant impermeable surface coverage.", ukApplicability: ["UK rail depots and maintenance facilities", "TfL and Network Rail large-roofed assets", "London Overground and rail operations facilities"], insight: "Large rail depots have extensive impermeable roofing that contributes significantly to urban runoff. Rainwater harvesting at depot scale delivers meaningful drainage relief with operational water reuse benefits, at relatively low capital cost.", tags: ["rail", "flooding", "surface water", "heavy rainfall", "SuDS", "rainwater harvesting", "drainage", "depot", "London", "TfL", "urban flooding", "UK"] },

  ID_80: { title: "Berlin BVG Green Tramway Tracks", sector: "Rail", hook: "Grass-covered tram tracks · urban cooling · reduced surface water runoff · 22-line city tram network", hazards: { cause: ["High temperatures", "Heavy rainfall"], effect: ["Urban Heat Island effect", "Surface water flooding", "Urban overheating"] }, assets: ["Rail track", "Trams"], measures: ["Grass and vegetation cover on tram tracks", "Substrate layer installation", "Urban cooling through evapotranspiration", "Nature-based surface water management"], ukRegion: "Applicable UK-wide", cost: "Variable per project; Adlershof II line funded by EU/Berlin sustainable development programme", costBand: "Under £1m–£1m", summary: "Berlin's BVG tram network has progressively installed grass and vegetation cover on tram track corridors as a nature-based adaptation to urban heat and surface water flooding. The grass substrate cools the urban microclimate through evapotranspiration, reduces surface water runoff, and improves air quality — all while reducing track maintenance noise. Mandated by Berlin's Energy Turnaround Act 2016 and the Berlin Energy and Climate Programme 2030.", transferability: "High", transferabilityNote: "Directly applicable to UK tram and light rail systems (Midland Metro, Nottingham Express Transit, Edinburgh Trams, Manchester Metrolink) where track corridors run through urban streets. A low-cost, easily integrated adaptation with immediate urban cooling and drainage benefits.", ukApplicability: ["Midland Metro tram network", "Nottingham Express Transit", "Edinburgh Trams", "Manchester Metrolink urban sections", "Future UK tram extensions"], insight: "Green tram tracks deliver triple value: heat island mitigation, surface water attenuation, and biodiversity gain — all from a substrate and planting intervention that also reduces maintenance costs. The substrate must be replaced every 2–5 years but costs are comparable to conventional track maintenance.", tags: ["rail", "tram", "light rail", "heat", "high temperatures", "urban heat island", "flooding", "surface water", "nature-based", "green infrastructure", "urban cooling", "Berlin", "SuDS"] },

  ID_81: { title: "Queensland Foamed Bitumen Road Restoration", sector: "Highways", hook: "Flood-resistant pavement · slope stabilisation · TMR restoration programme", hazards: { cause: ["Heavy rainfall", "Flooding", "Slope instability"], effect: ["Road damage", "Pavement failure", "Slope failure", "Road closure"] }, assets: ["Road pavement", "Highway formation", "Road base", "Cuttings and embankments"], measures: ["Foamed bitumen stabilisation", "Slope stabilisation works", "Flood-resistant road base", "Culvert upgrades"], ukRegion: "Applicable to UK flood-risk and upland roads", cost: "Not separately reported per site", costBand: "Under £1m–£10m per site", summary: "Queensland's Transport and Main Roads department adopted foamed bitumen as a standard restoration technique for flood-damaged highways across the state, providing water-resistant pavement and stabilising underlying road formations, including slope works on cut-and-fill sections.", transferability: "Medium", transferabilityNote: "Foamed bitumen stabilisation and slope works applicable to UK rural highways and A-roads in flood-prone and upland areas. The whole-programme approach to network restoration is directly relevant to Highways England and local authority recovery planning.", ukApplicability: ["Wales", "UK rural flood-affected roads", "A-roads in upland areas", "Local authority highway restoration", "National Highways slope management"], insight: "Treating flood damage restoration as an opportunity to upgrade pavement specification — not just reinstate like-for-like — delivers long-term resilience at marginal additional cost.", tags: ["highways", "roads", "motorway", "slope stabilisation", "slope instability", "flooding", "road restoration", "pavement", "embankment", "cutting", "geohazard", "flood-resistant"] },
};

// Sector mapping from PDF metadata values to display sectors
const SECTOR_MAP: Record<string, string> = {
  "railways": "Rail", "rail": "Rail",
  "aviation": "Aviation",
  "ports, coastal and offshore": "Maritime", "maritime": "Maritime", "ports": "Maritime",
  "highways": "Highways", "roads": "Highways",
  "inland waterways": "Maritime",
  "multiple": "Multiple",
};

function mapSector(raw?: string | null): string {
  if (!raw) return "Highways";
  const lower = raw.toLowerCase().trim();
  return SECTOR_MAP[lower] ?? raw;
}

function mapJsonToCaseStudy(json: any): CaseStudy {
  const id = json.trib_id;
  const override = SEED_OVERRIDES[id];
  const challengeText = normaliseBulletGlyphs(json.sections?.challenge ?? "");
  const adaptText = normaliseBulletGlyphs(json.sections?.adaptation_measures ?? "");
  const summaryFallback = challengeText
    ? challengeText.split(". ").slice(0, 3).join(". ") + "."
    : "";

  return {
    id,
    title: normaliseBulletGlyphs(override?.title ?? json.organisation ?? id),
    organisation: normaliseBulletGlyphs(json.organisation ?? ""),
    sector: override?.sector ?? mapSector(json.transport_subsector),
    hook: normaliseBulletGlyphs(override?.hook ?? (json.measure_title ?? "").slice(0, 80)),
    hazards: override?.hazards ?? {
      cause: json.hazard_cause ? json.hazard_cause.split(", ").filter(Boolean) : [],
      effect: json.hazard_effect ? json.hazard_effect.split(", ").filter(Boolean) : [],
    },
    summary: normaliseBulletGlyphs(override?.summary ?? json.case_study_text ?? summaryFallback),
    transferability: override?.transferability ?? "Medium",
    transferabilityNote: normaliseBulletGlyphs(
      override?.transferabilityNote ??
        json.sections?.applicability?.split(". ").slice(0, 2).join(". ") ??
        "—"
    ),
    ukApplicability: override?.ukApplicability ?? [],
    insight: normaliseBulletGlyphs(override?.insight ?? json.sections?.evaluation?.split(". ").slice(0, 2).join(". ") ?? "—"),
    measures: (override?.measures ?? (json.measures?.length ? json.measures : json.measure_title ? [json.measure_title] : []))
      .map((m: string) => normaliseBulletGlyphs(m)),
    assets: override?.assets ?? (json.asset_type ? json.asset_type.split(", ").filter(Boolean) : []),
    tags: override?.tags ?? [],
    location: json.sections ? (json.organisation ?? "—") : "—",
    ukRegion: override?.ukRegion ?? "—",
    year: "—",
    cost: override?.cost ?? "—",
    costBand: override?.costBand ?? "—",
    sections: normaliseSections(json.sections),
    source_pdf_url: json.source_pdf_url,
  };
}

// Load from JSON file, falling back to hardcoded overrides
let _caseStudies: CaseStudy[] | null = null;

function loadCaseStudies(): CaseStudy[] {
  if (_caseStudies) return _caseStudies;

  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    const jsonData = require("@/data/case-studies.json") as any[];
    _caseStudies = jsonData.map(mapJsonToCaseStudy);
    return _caseStudies;
  } catch {
    // Fall back to the 7 hand-curated overrides
    _caseStudies = Object.entries(SEED_OVERRIDES).map(([id, o]) => ({
      id,
      title: o.title ?? id,
      organisation: o.title ?? "",
      sector: o.sector ?? "Highways",
      hook: o.hook ?? "",
      hazards: o.hazards ?? { cause: [], effect: [] },
      summary: o.summary ?? "",
      transferability: o.transferability ?? "Medium",
      transferabilityNote: o.transferabilityNote ?? "—",
      ukApplicability: o.ukApplicability ?? [],
      insight: o.insight ?? "—",
      measures: o.measures ?? [],
      assets: o.assets ?? [],
      tags: o.tags ?? [],
      location: "—",
      ukRegion: o.ukRegion ?? "—",
      year: "—",
      cost: o.cost ?? "—",
      costBand: o.costBand ?? "—",
    source_pdf_url: (o as { source_pdf_url?: string }).source_pdf_url ?? getCaseStudyPdfUrl({ id, title: o.title ?? id }),
    }));
    return _caseStudies;
  }
}

export const CASE_STUDIES: CaseStudy[] = loadCaseStudies();
